/**
 * Alex - Video Producer Handoff Types (DEFERRED)
 *
 * IMPLEMENTATION STATUS: DEFERRED FOR FUTURE DEVELOPMENT
 */

// DEFERRED: Handoff data received from David (Creative Director)
export interface DavidToAlexHandoffData {
  readonly sessionId: string;
  readonly timestamp: Date;
  readonly version: '1.0';

  // Creative brief and concept
  readonly creativeBrief: CreativeBrief;
  readonly visualConcept: VisualConcept;
  readonly brandGuidelines: BrandGuidelines;

  // Generated assets from David
  readonly generatedAssets: GeneratedAsset[];
  readonly sceneComposition: SceneComposition[];
  readonly styleGuide: StyleGuide;

  // Production requirements
  readonly productionRequirements: ProductionRequirements;
  readonly deliverySpecs: DeliverySpecifications;
  readonly approvalStatus: ApprovalStatus;
}

// DEFERRED: Creative brief from David
export interface CreativeBrief {
  readonly concept: string;
  readonly targetAudience: string;
  readonly keyMessages: string[];
  readonly callToAction: string;
  readonly tone: string;
  readonly duration: number; // preferred duration in seconds
}

// DEFERRED: Visual concept direction
export interface VisualConcept {
  readonly theme: string;
  readonly colorPalette: any;
  readonly visualStyle: string;
}

// DEFERRED: Brand guidelines for production
export interface BrandGuidelines {
  readonly brandName: string;
  readonly logoUrl: string;
  readonly primaryColors: string[];
  readonly secondaryColors: string[];
  readonly typography: TypographyGuide;
  readonly restrictions: BrandRestriction[];
}

// DEFERRED: Typography specifications
export interface TypographyGuide {
  readonly primaryFont: string;
  readonly secondaryFont: string;
  readonly headingStyle: TextStyle;
  readonly bodyStyle: TextStyle;
}

// DEFERRED: Text style specifications
export interface TextStyle {
  readonly fontSize: number;
  readonly fontWeight: string;
  readonly lineHeight: number;
  readonly color: string;
}

// DEFERRED: Brand restrictions and requirements
export interface BrandRestriction {
  readonly type: 'color' | 'content' | 'placement' | 'timing';
  readonly description: string;
  readonly severity: 'warning' | 'error';
}

// DEFERRED: Assets generated by David
export interface GeneratedAsset {
  readonly assetId: string;
  readonly type: 'product-shot' | 'lifestyle' | 'background' | 'logo';
  readonly url: string;
  readonly dimensions: { width: number; height: number };
  readonly description: string;
  readonly usageGuidelines: string;
}

// DEFERRED: Scene composition from David
export interface SceneComposition {
  readonly sceneId: string;
  readonly duration: number;
  readonly description: string;
  readonly keyAssets: string[]; // asset IDs
  readonly transitions: TransitionSpec[];
  readonly voiceoverScript?: string;
}

// DEFERRED: Transition specifications
export interface TransitionSpec {
  readonly type: 'fade' | 'cut' | 'slide' | 'zoom';
  readonly duration: number;
  readonly easing: string;
}

// DEFERRED: Style guide from David
export interface StyleGuide {
  readonly overallStyle: string;
  readonly lighting: LightingGuide;
  readonly cameraWork: CameraGuide;
  readonly effects: EffectGuide[];
}

// DEFERRED: Lighting specifications
export interface LightingGuide {
  readonly mood: 'bright' | 'dramatic' | 'soft' | 'natural';
  readonly keyLighting: string;
  readonly shadowIntensity: number;
}

// DEFERRED: Camera work specifications
export interface CameraGuide {
  readonly shots: CameraShot[];
  readonly movement: CameraMovement[];
  readonly angles: CameraAngle[];
}

// DEFERRED: Camera shot specifications
export interface CameraShot {
  readonly type: 'close-up' | 'medium' | 'wide' | 'macro';
  readonly duration: number;
  readonly description: string;
}

// DEFERRED: Camera movement specifications
export interface CameraMovement {
  readonly type: 'static' | 'pan' | 'zoom' | 'dolly';
  readonly speed: 'slow' | 'medium' | 'fast';
  readonly direction?: string;
}

// DEFERRED: Camera angle specifications
export interface CameraAngle {
  readonly type: 'eye-level' | 'high' | 'low' | 'dutch';
  readonly purpose: string;
}

// DEFERRED: Effect specifications
export interface EffectGuide {
  readonly effectType: string;
  readonly intensity: number;
  readonly timing: 'start' | 'middle' | 'end' | 'throughout';
  readonly parameters: Record<string, any>;
}

// DEFERRED: Production requirements
export interface ProductionRequirements {
  readonly targetDuration: number; // seconds
  readonly resolution: any;
  readonly frameRate: number;
  readonly aspectRatio: string;
  readonly deliveryFormat: any;
  readonly qualityLevel: 'standard' | 'high' | 'premium';
}

// DEFERRED: Delivery specifications
export interface DeliverySpecifications {
  readonly platforms: DeliveryPlatform[];
  readonly fileSize: FileSizeLimit;
  readonly compressionSettings: CompressionSettings;
  readonly deliveryDeadline: Date;
}

// DEFERRED: Target delivery platforms
export interface DeliveryPlatform {
  readonly platform: 'web' | 'mobile' | 'social' | 'tv';
  readonly specifications: PlatformSpec;
}

// DEFERRED: Platform-specific specifications
export interface PlatformSpec {
  readonly maxDuration: number;
  readonly preferredAspectRatio: string;
  readonly maxFileSize: number;
  readonly requiredFormats: any[];
}

// DEFERRED: File size limitations
export interface FileSizeLimit {
  readonly maximum: number; // MB
  readonly preferred: number; // MB
  readonly acceptable: number; // MB
}

// DEFERRED: Compression settings
export interface CompressionSettings {
  readonly codec: string;
  readonly bitrate: number;
  readonly quality: number; // 0-100
  readonly preset: string;
}

// DEFERRED: Approval status from David
export interface ApprovalStatus {
  readonly approved: boolean;
  readonly approvedBy: string;
  readonly approvedAt: Date;
  readonly conditions?: string[];
  readonly revisionRequests?: RevisionRequest[];
}

// DEFERRED: Revision requests
export interface RevisionRequest {
  readonly requestId: string;
  readonly description: string;
  readonly priority: 'low' | 'medium' | 'high' | 'critical';
  readonly affectedScenes: string[];
}